name: Gatsby Publish

on:
  push:
    branches:
      - main

# Environment variables available to all jobs and steps in this workflow
env:
  GATSBY_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
  GATSBY_CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
  GATSBY_GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          gatsby-args: --prefix-paths
