name: Pull Request - Lint

on:
  pull_request:
    types: [ opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build:
    name: Pull Request - Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Yarn Install
        run: yarn install --frozen-lockfile
      - name: Yarn Lint
        run: yarn lint
